# Eigen Values and Eigen Vectors

### Calculate the eigenvalues and eigenvectors of the matrix

In [3]:
import numpy as np
I=np.array([[4,3,2],[1,4,1],[3,10,4]])
print("Given Matrix")
print(I)
print()
x=np.linalg.eigvals(I)
y=np.linalg.eig(I)
print("Eigen values",x)
print("Eigen vectors",y)

Given Matrix
[[ 4  3  2]
 [ 1  4  1]
 [ 3 10  4]]

Eigen values [8.98205672 2.12891771 0.88902557]
Eigen vectors (array([8.98205672, 2.12891771, 0.88902557]), array([[-0.49247712, -0.82039552, -0.42973429],
       [-0.26523242,  0.14250681, -0.14817858],
       [-0.82892584,  0.55375355,  0.89071407]]))


### Calculate the eigen values and eigenvectors of the given matrix

In [4]:
import numpy as np
I=np.array([[1,-3,3],[3,-5,3],[6,-6,4]])
print("Given Matrix")
print(I)
print()
x=np.linalg.eigvals(I)
y=np.linalg.eig(I)
print("Eigen values",x)
print("Eigen vectors",y)

Given Matrix
[[ 1 -3  3]
 [ 3 -5  3]
 [ 6 -6  4]]

Eigen values [ 4. -2. -2.]
Eigen vectors (array([ 4., -2., -2.]), array([[ 0.40824829, -0.40824829, -0.30502542],
       [ 0.40824829,  0.40824829, -0.808424  ],
       [ 0.81649658,  0.81649658, -0.50339858]]))


# Properties of eigenvalues and eigenvectors

##### For an n x n matrix the number of eigen values is always less than or equal to n.

##### The sum of eigen values is equal to the diagonal elements of matrix

##### The product of eigen values is equal to the determinant of the matrix

##### The eigen value of an identity matrix is 1

##### The eigenvalues of a triangular matrix is the diagonal elements

##### For a skew symmetric matrix, the eigenvalues are either purely imaginary or zero

##### For orthogonal matrix the length of eigenvalues equal to 1

##### For idempotent (A^2=A) matrix the eigenvalues are 0 and 1 

In [5]:
import math 
from math import *
import numpy as np
from numpy import *

## Property 2

In [4]:
import numpy as np
A=np.array([[1,2,3],[2,3,5],[3,1,1]])
print("Given Matrix")
print(A)
x=np.linalg.eigvals(A)
y=round(sum(x))
print(x)
print(y)
z=np.trace(A)
print(z)

Given Matrix
[[1 2 3]
 [2 3 5]
 [3 1 1]]
[ 6.70681662 -1.38350231 -0.32331432]
5
5


## Property 3

In [11]:
import numpy as np
A=np.array([[1,2,3],[1,3,5],[4,1,2]])
print("Given Matrix")
print(A)
x=np.linalg.eigvals(A)
y=np.round(np.prod(x))
z=np.round(np.linalg.det(A))
print(y)
print(z)

Given Matrix
[[1 2 3]
 [1 3 5]
 [4 1 2]]
(4+0j)
4.0


## Property 4

In [13]:
A=np.eye(3)
print(A)
x=np.linalg.eigvals(A)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


# Property 5

In [14]:
A=np.array([[1,2,3],[0,3,5],[0,0,2]])# Triangular Matrix
x=np.linalg.eigvals(A)
print(x)

[1. 3. 2.]


# Property 6

In [21]:
A=np.array([[0,-1],[1,0]])
x=np.round(np.linalg.eigvals(A))
print(x)

[0.+1.j 0.-1.j]


In [20]:
A=np.array([[0,1,-1],[-1,0,1],[1,-1,0]])
x=np.round(np.linalg.eigvals(A))
print(x)

[0.+2.j 0.-2.j 0.+0.j]


## Property 7

In [25]:
A=np.array([[2/3,1/3,1/3],[-2/3,1/3,2/3],[1/3,-2/3,2/3]])
x=np.round(np.linalg.eigvals(A))
print(x)
print(np.sum(x))

[1.+0.j 0.+1.j 0.-1.j]
(1+0j)


## Property 8

In [27]:
A=np.array([[1,2,0],[0,1,0],[0,0,0]])
x=np.round(np.linalg.eigvals(A))
print(x)

[1. 1. 0.]


# Diagonalisation of a Square Matrix

##### Given the matrix A, let the matrix of eigen vectors of A and P and the inverse of the matrix P be I. Then the diagonalised matrix is given by the equation IAP=D

In [4]:
import numpy as np
from math import *
A=np.mat([[2,-2,3],[1,1,1],[1,3,-1]])
X,P=np.linalg.eig(A)
I=np.linalg.eig(A)
I=np.linalg.inv(P)
Z=np.around(I*A*P)
for i in range(len(Z)):
    for j in range(len(Z)):
        if Z[i,j]==-0:
            Z[i,j]=0
print("The final diagonalised matrix is")
print(Z)
print("Eigen Vectors", P)
print("Eigen VAlues", X)

The final diagonalised matrix is
[[ 3.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -2.]]
Eigen Vectors [[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]
Eigen VAlues [ 3.  1. -2.]


## Cayley Hamilton Theorem

### Every non singular square matrix satisfy its characteristic equation

In [1]:
import numpy as np
A=np.mat([[2,3],[4,5]])
from math import *
X=np.poly(A)
print("The coefficients of the characeteristic equation are",X)

trace_A=np.trace(A)
print("Trace=",trace_A)
det_A=np.linalg.det(A)
print("Determinant=",det_A)
I=np.eye(len(A))
print(I)
P=A*A-trace_A*A+det_A*I
print(P)

The coefficients of the characeteristic equation are [ 1. -7. -2.]
Trace= 7
Determinant= -2.0
[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]


In [6]:
from sympy import *
from math import *
from numpy import *
import numpy as np

n=int(input("Enter the order of the matris"))
print("Enter by single line separated by space")
elements=list(map(int,input().split()))
A=np.matrix(elements).reshape(n,n)
s=0
print()
print("The matrix is ")
print(A)
I=eye(len(A),len(A))
print(I)
ce=np.poly(A)
print(ce)
ce=ce.round()
print("The coefficients of the characteristic equation",ce)
for i in range(len(ce)):
    eq=ce[i]*I*(A**(len(ce)-i))
    s=s+eq
print()
s

Enter the order of the matris3
Enter by single line separated by space
1 3 4 2 5 4 3 4 5

The matrix is 
[[1 3 4]
 [2 5 4]
 [3 4 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[  1. -11.   1.  13.]
The coefficients of the characteristic equation [  1. -11.   1.  13.]



matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## Verify Cayley Hamilton Theorem

In [7]:
from sympy import *
from math import *
from numpy import *
import numpy as np

n=int(input("Enter the order of the matris"))
print("Enter by single line separated by space")
elements=list(map(int,input().split()))
A=np.matrix(elements).reshape(n,n)
s=0
print()
print("The matrix is ")
print(A)
I=eye(len(A),len(A))
print(I)
ce=np.poly(A)
print(ce)
ce=ce.round()
print("The coefficients of the characteristic equation",ce)
for i in range(len(ce)):
    eq=ce[i]*I*(A**(len(ce)-i))
    s=s+eq
print()
s

Enter the order of the matris3
Enter by single line separated by space
3 1 2 1 2 0 0 1 3

The matrix is 
[[3 1 2]
 [1 2 0]
 [0 1 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[  1.  -8.  20. -17.]
The coefficients of the characteristic equation [  1.  -8.  20. -17.]



matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
from sympy import *
from math import *
from numpy import *
import numpy as np

n=int(input("Enter the order of the matris"))
print("Enter by single line separated by space")
elements=list(map(int,input().split()))
A=np.matrix(elements).reshape(n,n)
s=0
print()
print("The matrix is ")
print(A)
I=eye(len(A),len(A))
print(I)
ce=np.poly(A)
print(ce)
ce=ce.round()
print("The coefficients of the characteristic equation",ce)
for i in range(len(ce)):
    eq=ce[i]*I*(A**(len(ce)-i))
    s=s+eq
print()
s

Enter the order of the matris4
Enter by single line separated by space
1 3 5 7 2 4 6 8 4 3 5 2 6 4 5 1

The matrix is 
[[1 3 5 7]
 [2 4 6 8]
 [4 3 5 2]
 [6 4 5 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 1.00000000e+00 -1.10000000e+01 -8.90000000e+01  7.30000000e+01
 -3.33472454e-14]
The coefficients of the characteristic equation [  1. -11. -89.  73.  -0.]



matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
from sympy import *
from math import *
from numpy import *
import numpy as np

n=int(input("Enter the order of the matris"))
print("Enter by single line separated by space")
elements=list(map(int,input().split()))
A=np.matrix(elements).reshape(n,n)
s=0
print()
print("The matrix is ")
print(A)
I=eye(len(A),len(A))
print(I)
ce=np.poly(A)
print(ce)
ce=ce.round()
print("The coefficients of the characteristic equation",ce)
for i in range(len(ce)):
    eq=ce[i]*I*(A**(len(ce)-i))
    s=s+eq
print()
s

Enter the order of the matris4
Enter by single line separated by space
3 1 0 4 2 0 7 3 1 2 8 4 4 3 7 2

The matrix is 
[[3 1 0 4]
 [2 0 7 3]
 [1 2 8 4]
 [4 3 7 2]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[  1. -13. -23. 156. 299.]
The coefficients of the characteristic equation [  1. -13. -23. 156. 299.]



matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])